services:
  postgres:
    container_name: postgres_db
    image: postgres:16.3
    tty: true
    restart: always
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  user-service:
    container_name: monorepo-user-service
    restart: unless-stopped
    build:
      context: .
      args:
        - APP=user-service
    ports:
      - "$PORT_USER_API:$PORT_USER_API"
      - "5870:5870"

  url-service:
    container_name: monorepo-url-service
    restart: unless-stopped
    build:
      context: .
      args:
        - APP=url-service
    ports:
      - "$PORT_URL_API:$PORT_URL_API"
      - "5880:5880"

volumes:
  pgdata:
  node_modules: