services:
  postgres:
    container_name: postgres_db
    image: postgres:16.3
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  user-service:
    container_name: monorepo-user-service
    restart: unless-stopped
    build:
      context: .
      args:
        - APP=user-service
    ports:
      - "$PORT_USER_API:$PORT_USER_API"
      - "5870:5870"
    depends_on: 
      - postgres

  url-service:
    container_name: monorepo-url-service
    restart: unless-stopped
    build:
      context: .
      args:
        - APP=url-service
    ports:
      - "$PORT_URL_API:$PORT_URL_API"
      - "5880:5880"
    depends_on: 
      - postgres

volumes:
  pgdata:
  node_modules: